project:
  type: website

website:
  page-navigation: true
  title: "STAT 1010 - Fall 2022"
  description: "Homepage for STAT 1010 - Introduction to Business Statistics, Fall 2022."
  site-url: "https://sta210-s22.github.io/website/"

  repo-url: https://github.com/stats1010-f22/website
  repo-actions: [edit, issue]

  open-graph: true
  twitter-card:
    creator: "@nzgwynn"

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2022, gwynn sturdevant"
    background: "#D9E3E4"

  sidebar:
    background: "#D9E3E4"
    #logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: link
        href: https://github.com/sta1010-f22
        text: Course links
        menu:
          - text: Discussions
            url: https://edstem.org/us/courses/27622/discussion/
          - text: Gradescope
            url: https://www.gradescope.com/courses/433175
          - text: Canvas
            url: https://canvas.upenn.edu/courses/1680632/grades

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - href: course-overview.qmd
            text: Overview
          - href: course-syllabus.qmd
            text: Syllabus
          - href: course-support.qmd
            text: Support
          - href: course-team.qmd
            text: Teaching team
          - href: index.qmd
            text: Schedule
          - href: course-links.qmd
            text: Useful links
          - href: course-faq.qmd
            text: FAQ
      - section: "Computing"
        contents:
          - href: computing-access.qmd
            text: Access
          - href: computing-troubleshooting.qmd
            text: Troubleshooting
      # - section: "Project"
      #   contents:
      #     - href: project-description.qmd
      #       text: Description
      #     - href: project-tips-resources.qmd
      #       text: Tips + resources
      - section: "Weekly materials"
        contents:
          - href: weeks/week-1.qmd
            text: "Week 1"
          # - href: weeks/week-2.qmd
          #   text: "Week 2"
          # - href: weeks/week-3.qmd
          #   text: "Week 3"
          # - href: weeks/week-4.qmd
          #   text: "Week 4"
          # - href: weeks/week-5.qmd
          #   text: "Week 5"
          # - href: weeks/week-6.qmd
          #   text: "Week 6"
          # - href: weeks/week-7.qmd
          #   text: "Week 7"
          # - href: weeks/week-8.qmd
          #   text: "Week 8"
          # - href: weeks/week-9.qmd
          #   text: "Week 9"
          # - href: weeks/week-10.qmd
          #   text: "Week 10"
          # - href: weeks/week-11.qmd
          #   text: "Week 11"
          # - href: weeks/week-12.qmd
          #   text: "Week 12"
          # - href: weeks/week-13.qmd
          #   text: "Week 13"
          # - href: weeks/week-14.qmd
          #   text: "Week 14"
          # - href: weeks/week-15.qmd
          #   text: "Week 15"
      # - section: "Supplemental notes"
      #   contents:
      #     - href: supplemental/slr-derivations.qmd
      #       text: SLR derivations
      #     - href: supplemental/model-diagnostics-matrix.qmd
      #       text: Model diagnostics
      #     - href: supplemental/mlr-matrix.qmd
      #       text: MLR matrix notation
      #     - href: supplemental/log-transformations.qmd
      #       text: Log transformations
      #     - href: supplemental/model-selection-criteria.qmd
      #       text: Model selection criteria

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

editor: visual